const express = require("express");

const catalogueRoutes = require("./itemCatalogue/catalogueRoutes");
const categoryRoutes = require("./category/categoryRoutes");
const productCatalogueRoutes = require("./productCatalogue/productCatalogueRoutes");
const orderCartRoutes = require("./order/orderCartRoutes");
const userRoutes = require("./user/userRoutes");
const productionRoutes = require("./production/productionRoutes");
const storeRoutes = require("./store/storeRoutes");
const storeInventoryRoutes = require("./store/storeInventoryRoutes");
const bankRoutes = require("./payment/bankRoutes");
const cashCenterRoutes = require("./payment/cashCenterRoutes");
const currencyRoutes = require("./payment/currencyRoutes");
const recipientRoutes = require("./payment/recipientRoutes");
const mobileTransferRoutes = require("./payment/mobileTransferRoutes");
const outboundTransferRoutes = require("./payment/outboundTransferRoutes");
const inboundTransferRoutes = require("./payment/inboundTransferRoutes");
const walletTransferRoutes = require("./payment/walletTransferRoutes");
const startupRoutes = require("./IIO/startupIdeaRoutes");
const companyRoutes = require("./IIO/companyRoutes");
const stockAllocationRoutes = require("./IIO/stockAllocationRoutes");
const stockOrderTransferRoutes = require("./IIO/stockOrderTransferRoutes");
const vgcStockRoutes = require("./IIO/vgcRoutes");
const dividentRoutes = require("./IIO/dividendRoutes");
const investmentRoutes = require("./IIO/investmentRoutes");
const walletRoutes = require("./user/walletRoutes");
const mapTeamRoutes = require("./user/mapTeamRoutes");
const employeeRoutes = require("./user/employeeRoutes");
const deliveryRoutes = require("./user/addressRoutes");
const educationRoutes = require("./user/educationRoutes");
const jobExperienceRoutes = require("./user/jobExperienceRoutes");

const router = express.Router();

router.use("/category", categoryRoutes);
router.use("/category/itemCatalogue", catalogueRoutes);
router.use("/category/itemCatalogue/productCatalogue", productCatalogueRoutes);
router.use("/ordercart", orderCartRoutes);
router.use("/user", userRoutes);
router.use("/user/wallet", walletRoutes);
router.use("/user/map-team", mapTeamRoutes);
router.use("/user/employee", employeeRoutes);
router.use("/production", productionRoutes);
router.use("/store", storeRoutes);
router.use("/storeinventory", storeInventoryRoutes);
router.use("/user/bank", bankRoutes);
router.use("/bank/cashcenter", cashCenterRoutes);
router.use("/bank/currency", currencyRoutes);
router.use("/bank/recipient", recipientRoutes);
router.use("/bank/modiletransfer", mobileTransferRoutes);
router.use("/bank/outboundtransfer", outboundTransferRoutes);
router.use("/bank/inboundtransfer", inboundTransferRoutes);
router.use("/bank/wallettransfer", walletTransferRoutes);
router.use("/user/startup", startupRoutes);
router.use("/user/company", companyRoutes);
router.use("/user/stockAllocation", stockAllocationRoutes);
router.use("/user/stockOrderTransfer", stockOrderTransferRoutes);
router.use("/stock", vgcStockRoutes);
router.use("/stock/divident", dividentRoutes);
router.use("/stock/investment", investmentRoutes);
router.use("/user/delivery-address", deliveryRoutes);
router.use("/user/education", educationRoutes);
router.use("/user/job-experience", jobExperienceRoutes);

module.exports = router;
